# Librerias

In [47]:
import pandas as pd

# Ejercicios de Lectura de CSV
## Ejercicio 1
Leer el archivo CSV `datos_ejemplo.csv` y mostrar el contenido completo.

In [48]:
df = pd.read_csv('datos_ejemplo.csv')
display(df.head())

   id firstname   lastname                     email   birthdate
0   1     Kerry  O'Connell         Kerry16@gmail.com  1990-01-01
1   2     Ethel     Miller       Ethel14@hotmail.com  1985-05-12
2   3    Willie     Barton   Willie.Barton@gmail.com  1992-07-23
3   4     Ellis       Lowe      Ellis.Lowe@gmail.com  1988-11-30
4   5   Raymond     Miller  Raymond.Miller@gmail.com  1991-03-15

## Ejercicio 2
Leer el archivo CSV `datos_ejemplo.csv` y mostrar solo las columnas `firstname` y `lastname`.

In [49]:
df = pd.read_csv('datos_ejemplo.csv')
firstname_and_lastname = df[['firstname', 'lastname']]
display(firstname_and_lastname.head())

  firstname   lastname
0     Kerry  O'Connell
1     Ethel     Miller
2    Willie     Barton
3     Ellis       Lowe
4   Raymond     Miller

## Ejercicio 3
Leer el archivo CSV `datos_ejemplo.csv`, parsear la columna `birthdate` como fechas y establecerla como índice del DataFrame.

In [50]:
df = pd.read_csv('datos_ejemplo.csv')
df['birthdate'] = pd.to_datetime(df['birthdate'], format='%Y-%m-%d')
# df.index = df['birthdate']
display(df.head())

   id firstname   lastname                     email  birthdate
0   1     Kerry  O'Connell         Kerry16@gmail.com 1990-01-01
1   2     Ethel     Miller       Ethel14@hotmail.com 1985-05-12
2   3    Willie     Barton   Willie.Barton@gmail.com 1992-07-23
3   4     Ellis       Lowe      Ellis.Lowe@gmail.com 1988-11-30
4   5   Raymond     Miller  Raymond.Miller@gmail.com 1991-03-15

# Ejercicios de Selección, Filtrado y Creación de Nuevos DataFrames
## Ejercicio 1
Seleccionar y mostrar solo las filas donde el apellido sea `Miller`.

In [51]:
miller_rows = df[df['lastname'] == 'Miller']
display(miller_rows)

   id firstname lastname                     email  birthdate
1   2     Ethel   Miller       Ethel14@hotmail.com 1985-05-12
4   5   Raymond   Miller  Raymond.Miller@gmail.com 1991-03-15

## Ejercicio 2
Seleccionar y mostrar solo las filas donde la fecha de nacimiento sea posterior a `1990-01-01`.

In [52]:
after_1990 = df[df['birthdate'] > pd.Timestamp('1990-01-01')]
display(after_1990)

   id firstname  lastname                     email  birthdate
2   3    Willie    Barton   Willie.Barton@gmail.com 1992-07-23
4   5   Raymond    Miller  Raymond.Miller@gmail.com 1991-03-15
6   7       Joe      Rice           Joe55@gmail.com 1993-12-05
8   9    Maxine  Schinner      Maxine93@hotmail.com 1990-08-22

## Ejercicio 3
Crear un nuevo DataFrame con una columna adicional `fullname` que contenga el nombre completo (`firstname` + `lastname`).

In [53]:
df['full_name'] = df['firstname'] + ' ' + df['lastname']
display(df.head())

,id,firstname,lastname,email,birthdate,full_name
0,1,Kerry,O'Connell,Kerry16@gmail.com,1990-01-01,Kerry O'Connell
1,2,Ethel,Miller,Ethel14@hotmail.com,1985-05-12,Ethel Miller
2,3,Willie,Barton,Willie.Barton@gmail.com,1992-07-23,Willie Barton
3,4,Ellis,Lowe,Ellis.Lowe@gmail.com,1988-11-30,Ellis Lowe
4,5,Raymond,Miller,Raymond.Miller@gmail.com,1991-03-15,Raymond Miller

## Ejercicio 4
Seleccionar y mostrar solo las filas donde el nombre sea `Ellen`.

In [54]:
ellen_rows = df[df['firstname'] == 'Ellen']
display(ellen_rows)

   id firstname  lastname                email  birthdate       full_name
5   6     Ellen  Thompson  Ellen92@hotmail.com 1987-09-25  Ellen Thompson

## Ejercicio 5
Seleccionar y mostrar solo las filas donde el correo electrónico contenga `gmail.com`.

In [55]:
gmail_rows = df[df['email'].str.contains('gmail.com', na=False)]
display(gmail_rows)

,id,firstname,lastname,email,birthdate,full_name
0,1,Kerry,O'Connell,Kerry16@gmail.com,1990-01-01,Kerry O'Connell
2,3,Willie,Barton,Willie.Barton@gmail.com,1992-07-23,Willie Barton
3,4,Ellis,Lowe,Ellis.Lowe@gmail.com,1988-11-30,Ellis Lowe
4,5,Raymond,Miller,Raymond.Miller@gmail.com,1991-03-15,Raymond Miller
6,7,Joe,Rice,Joe55@gmail.com,1993-12-05,Joe Rice

## Ejercicio 6
Crear un nuevo DataFrame con una columna adicional `age` que contenga la edad calculada a partir de la fecha de nacimiento.

In [56]:
today = pd.Timestamp('today')
before_birthday = (
    (df['birthdate'].dt.month > today.month) |
    ((df['birthdate'].dt.month == today.month) & (df['birthdate'].dt.day > today.day))
)

df['age'] = today.year - df['birthdate'].dt.year - before_birthday.astype(int)
display(df.head())

,id,firstname,lastname,email,birthdate,full_name,age
0,1,Kerry,O'Connell,Kerry16@gmail.com,1990-01-01,Kerry O'Connell,36
1,2,Ethel,Miller,Ethel14@hotmail.com,1985-05-12,Ethel Miller,40
2,3,Willie,Barton,Willie.Barton@gmail.com,1992-07-23,Willie Barton,33
3,4,Ellis,Lowe,Ellis.Lowe@gmail.com,1988-11-30,Ellis Lowe,37
4,5,Raymond,Miller,Raymond.Miller@gmail.com,1991-03-15,Raymond Miller,34

## Ejercicio 7
Seleccionar y mostrar solo las filas donde la edad sea mayor a 30 años.

In [57]:
over_30_years = df[df['age'] > 30]
display(over_30_years)

,id,firstname,lastname,email,birthdate,full_name,age
0,1,Kerry,O'Connell,Kerry16@gmail.com,1990-01-01,Kerry O'Connell,36
1,2,Ethel,Miller,Ethel14@hotmail.com,1985-05-12,Ethel Miller,40
2,3,Willie,Barton,Willie.Barton@gmail.com,1992-07-23,Willie Barton,33
3,4,Ellis,Lowe,Ellis.Lowe@gmail.com,1988-11-30,Ellis Lowe,37
4,5,Raymond,Miller,Raymond.Miller@gmail.com,1991-03-15,Raymond Miller,34
5,6,Ellen,Thompson,Ellen92@hotmail.com,1987-09-25,Ellen Thompson,38
6,7,Joe,Rice,Joe55@gmail.com,1993-12-05,Joe Rice,32
7,8,Nathaniel,Legros,Nathaniel40@hotmail.com,1986-04-18,Nathaniel Legros,39
8,9,Maxine,Schinner,Maxine93@hotmail.com,1990-08-22,Maxine Schinner,35
9,10,Tim,Jacobson,Tim92@hotmail.com,1989-10-10,Tim Jacobson,36

## Ejercicio 8
Seleccionar y mostrar solo las filas donde el nombre completo contenga `Miller`.

In [58]:
miller_rows = df[df['full_name'].str.contains('Miller', na=False)]
display(miller_rows)

,id,firstname,lastname,email,birthdate,full_name,age
1,2,Ethel,Miller,Ethel14@hotmail.com,1985-05-12,Ethel Miller,40
4,5,Raymond,Miller,Raymond.Miller@gmail.com,1991-03-15,Raymond Miller,34

## Ejercicio 9
Crear un nuevo DataFrame con una columna adicional `domain` que contenga el dominio del correo electrónico.

In [59]:
df['domain'] = df['email'].str.split('@').str[1]
display(df.head())

,id,firstname,lastname,email,birthdate,full_name,age,domain
0,1,Kerry,O'Connell,Kerry16@gmail.com,1990-01-01,Kerry O'Connell,36,gmail.com
1,2,Ethel,Miller,Ethel14@hotmail.com,1985-05-12,Ethel Miller,40,hotmail.com
2,3,Willie,Barton,Willie.Barton@gmail.com,1992-07-23,Willie Barton,33,gmail.com
3,4,Ellis,Lowe,Ellis.Lowe@gmail.com,1988-11-30,Ellis Lowe,37,gmail.com
4,5,Raymond,Miller,Raymond.Miller@gmail.com,1991-03-15,Raymond Miller,34,gmail.com

## Ejercicio 10
Seleccionar y mostrar solo las filas donde el dominio del correo electrónico sea `hotmail.com`.

In [60]:
hotmail_rows = df[df['domain'] == 'hotmail.com']
display(hotmail_rows)

,id,firstname,lastname,email,birthdate,full_name,age,domain
1,2,Ethel,Miller,Ethel14@hotmail.com,1985-05-12,Ethel Miller,40,hotmail.com
5,6,Ellen,Thompson,Ellen92@hotmail.com,1987-09-25,Ellen Thompson,38,hotmail.com
7,8,Nathaniel,Legros,Nathaniel40@hotmail.com,1986-04-18,Nathaniel Legros,39,hotmail.com
8,9,Maxine,Schinner,Maxine93@hotmail.com,1990-08-22,Maxine Schinner,35,hotmail.com
9,10,Tim,Jacobson,Tim92@hotmail.com,1989-10-10,Tim Jacobson,36,hotmail.com

# Ejercicios de Agrupación, Ordenación y Unión
## Ejercicio 1
Agrupar por apellido y contar el número de ocurrencias de cada apellido.

In [61]:
counts_by_lastname = df.groupby('lastname').size().sort_values(ascending=False)
display(counts_by_lastname)

lastname
Miller       2
Barton       1
Jacobson     1
Legros       1
Lowe         1
O'Connell    1
Rice         1
Schinner     1
Thompson     1
dtype: int64

## Ejercicio 2
Ordenar el DataFrame por fecha de nacimiento en orden ascendente.

In [62]:
sorted_by_birthdate = df.sort_values('birthdate', ascending=True)
display(sorted_by_birthdate)

,id,firstname,lastname,email,birthdate,full_name,age,domain
1,2,Ethel,Miller,Ethel14@hotmail.com,1985-05-12,Ethel Miller,40,hotmail.com
7,8,Nathaniel,Legros,Nathaniel40@hotmail.com,1986-04-18,Nathaniel Legros,39,hotmail.com
5,6,Ellen,Thompson,Ellen92@hotmail.com,1987-09-25,Ellen Thompson,38,hotmail.com
3,4,Ellis,Lowe,Ellis.Lowe@gmail.com,1988-11-30,Ellis Lowe,37,gmail.com
9,10,Tim,Jacobson,Tim92@hotmail.com,1989-10-10,Tim Jacobson,36,hotmail.com
0,1,Kerry,O'Connell,Kerry16@gmail.com,1990-01-01,Kerry O'Connell,36,gmail.com
8,9,Maxine,Schinner,Maxine93@hotmail.com,1990-08-22,Maxine Schinner,35,hotmail.com
4,5,Raymond,Miller,Raymond.Miller@gmail.com,1991-03-15,Raymond Miller,34,gmail.com
2,3,Willie,Barton,Willie.Barton@gmail.com,1992-07-23,Willie Barton,33,gmail.com
6,7,Joe,Rice,Joe55@gmail.com,1993-12-05,Joe Rice,32,gmail.com

## Ejercicio 3
Unir dos DataFrames creados a partir del archivo CSV original.

In [63]:
df_test = pd.read_csv('datos_ejemplo.csv')

df1 = df_test[['id', 'firstname', 'lastname']].copy()
df2 = df_test[['id', 'email', 'birthdate']].copy()

merged = pd.merge(df1, df2, on='id', how='inner')
display(merged.head())

   id firstname   lastname                     email   birthdate
0   1     Kerry  O'Connell         Kerry16@gmail.com  1990-01-01
1   2     Ethel     Miller       Ethel14@hotmail.com  1985-05-12
2   3    Willie     Barton   Willie.Barton@gmail.com  1992-07-23
3   4     Ellis       Lowe      Ellis.Lowe@gmail.com  1988-11-30
4   5   Raymond     Miller  Raymond.Miller@gmail.com  1991-03-15

## Ejercicio 4
Agrupar por dominio del correo electrónico y contar el número de ocurrencias de cada dominio.

In [64]:
counts_by_domain = df.groupby('domain').size().sort_values(ascending=False)
display(counts_by_domain)

domain
gmail.com      5
hotmail.com    5
dtype: int64

## Ejercicio 5
Ordenar el DataFrame por nombre completo en orden descendente.

In [65]:
sorted_by_fullname_desc = df.sort_values('full_name', ascending=False)
display(sorted_by_fullname_desc)

,id,firstname,lastname,email,birthdate,full_name,age,domain
2,3,Willie,Barton,Willie.Barton@gmail.com,1992-07-23,Willie Barton,33,gmail.com
9,10,Tim,Jacobson,Tim92@hotmail.com,1989-10-10,Tim Jacobson,36,hotmail.com
4,5,Raymond,Miller,Raymond.Miller@gmail.com,1991-03-15,Raymond Miller,34,gmail.com
7,8,Nathaniel,Legros,Nathaniel40@hotmail.com,1986-04-18,Nathaniel Legros,39,hotmail.com
8,9,Maxine,Schinner,Maxine93@hotmail.com,1990-08-22,Maxine Schinner,35,hotmail.com
0,1,Kerry,O'Connell,Kerry16@gmail.com,1990-01-01,Kerry O'Connell,36,gmail.com
6,7,Joe,Rice,Joe55@gmail.com,1993-12-05,Joe Rice,32,gmail.com
1,2,Ethel,Miller,Ethel14@hotmail.com,1985-05-12,Ethel Miller,40,hotmail.com
3,4,Ellis,Lowe,Ellis.Lowe@gmail.com,1988-11-30,Ellis Lowe,37,gmail.com
5,6,Ellen,Thompson,Ellen92@hotmail.com,1987-09-25,Ellen Thompson,38,hotmail.com

## Ejercicio 6
Unir dos DataFrames utilizando la columna `id` como clave.

In [66]:
df_test = pd.read_csv('datos_ejemplo.csv')

left = df_test[['id', 'firstname', 'lastname']].copy()
right = df_test[['id', 'email']].copy()

joined_on_id = left.merge(right, on='id', how='inner')
display(joined_on_id.head())

   id firstname   lastname                     email
0   1     Kerry  O'Connell         Kerry16@gmail.com
1   2     Ethel     Miller       Ethel14@hotmail.com
2   3    Willie     Barton   Willie.Barton@gmail.com
3   4     Ellis       Lowe      Ellis.Lowe@gmail.com
4   5   Raymond     Miller  Raymond.Miller@gmail.com

## Ejercicio 7
Agrupar por año de nacimiento y contar el número de ocurrencias de cada año.

In [67]:
df['birth_year'] = df['birthdate'].dt.year
counts_by_year = df.groupby('birth_year').size().sort_values(ascending=False)
display(counts_by_year)

birth_year
1990    2
1985    1
1986    1
1988    1
1987    1
1989    1
1991    1
1992    1
1993    1
dtype: int64

## Ejercicio 8
Ordenar el DataFrame por apellido en orden ascendente y luego por nombre en orden descendente.

In [68]:
sorted_multi = df.sort_values(['lastname', 'firstname'], ascending=[True, False])
display(sorted_multi)

,id,firstname,lastname,email,birthdate,full_name,age,domain,birth_year
2,3,Willie,Barton,Willie.Barton@gmail.com,1992-07-23,Willie Barton,33,gmail.com,1992
9,10,Tim,Jacobson,Tim92@hotmail.com,1989-10-10,Tim Jacobson,36,hotmail.com,1989
7,8,Nathaniel,Legros,Nathaniel40@hotmail.com,1986-04-18,Nathaniel Legros,39,hotmail.com,1986
3,4,Ellis,Lowe,Ellis.Lowe@gmail.com,1988-11-30,Ellis Lowe,37,gmail.com,1988
4,5,Raymond,Miller,Raymond.Miller@gmail.com,1991-03-15,Raymond Miller,34,gmail.com,1991
1,2,Ethel,Miller,Ethel14@hotmail.com,1985-05-12,Ethel Miller,40,hotmail.com,1985
0,1,Kerry,O'Connell,Kerry16@gmail.com,1990-01-01,Kerry O'Connell,36,gmail.com,1990
6,7,Joe,Rice,Joe55@gmail.com,1993-12-05,Joe Rice,32,gmail.com,1993
8,9,Maxine,Schinner,Maxine93@hotmail.com,1990-08-22,Maxine Schinner,35,hotmail.com,1990
5,6,Ellen,Thompson,Ellen92@hotmail.com,1987-09-25,Ellen Thompson,38,hotmail.com,1987

## Ejercicio 9
Unir dos DataFrames utilizando la columna `email` como clave.

In [69]:
df_test = pd.read_csv('datos_ejemplo.csv')

a = df_test[['email', 'firstname', 'lastname']].copy()
a['fullname'] = a['firstname'] + ' ' + a['lastname']
a = a[['email', 'fullname']]

b = df_test[['email', 'birthdate']].copy()

joined_on_email = a.merge(b, on='email', how='inner')
display(joined_on_email.head())

                      email         fullname   birthdate
0         Kerry16@gmail.com  Kerry O'Connell  1990-01-01
1       Ethel14@hotmail.com     Ethel Miller  1985-05-12
2   Willie.Barton@gmail.com    Willie Barton  1992-07-23
3      Ellis.Lowe@gmail.com       Ellis Lowe  1988-11-30
4  Raymond.Miller@gmail.com   Raymond Miller  1991-03-15

## Ejercicio 10
Agrupar por nombre y contar el número de ocurrencias de cada nombre.

In [70]:
counts_by_name = df.groupby('firstname').size().sort_values(ascending=False)
display(counts_by_name)

firstname
Ellen        1
Ellis        1
Ethel        1
Joe          1
Kerry        1
Maxine       1
Nathaniel    1
Raymond      1
Tim          1
Willie       1
dtype: int64